# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/HP/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-15524-DESKTOP-9DNF9CE/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/FYP/final/top.cache/wt [current_project]
set_property parent.project_path D:/FYP/final/top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FYP/final/top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/FYP/final/top.srcs/sources_1/new/Sha3_256.sv
  D:/FYP/final/top.srcs/sources_1/new/chi.sv
  D:/FYP/final/top.srcs/sources_1/new/fn_top.sv
  D:/FYP/final/top.srcs/sources_1/new/iota.sv
  D:/FYP/final/top.srcs/sources_1/new/padding.sv
  D:/FYP/final/top.srcs/sources_1/new/pi.sv
  D:/FYP/final/top.srcs/sources_1/new/rho.sv
  D:/FYP/final/top.srcs/sources_1/new/theta.sv
  D:/FYP/final/top.srcs/sources_1/new/top.sv
  D:/FYP/final/top.srcs/sources_1/new/topp.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FYP/final/top.srcs/constrs_1/imports/Downloads/Arty-A7-100-Master.xdc
set_property used_in_implementation false [get_files D:/FYP/final/top.srcs/constrs_1/imports/Downloads/Arty-A7-100-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top topp -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file topp_utilization_synth.rpt -pb topp_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
