// Generated by CIRCT firtool-1.62.1
module PolynomialAdder(
  input        clock,
               reset,
  input  [7:0] io_add1,
               io_add2,
  output [7:0] io_res
);

  reg [7:0] resultReg;
  always @(posedge clock) begin
    if (reset)
      resultReg <= 8'h0;
    else
      resultReg <= io_add1 + io_add2;
  end // always @(posedge)
  assign io_res = resultReg;
endmodule