# -*- coding: utf-8 -*-
"""H-Hash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOmLKCjTTQFcCQN0jVXk1MlPGiWqsPlu
"""

from hashlib import sha256

def _h(input_bytes):
    """
    H: B* -> B^32
    """
    return sha256(input_bytes).digest()

input_bytes = [
    [1, 1, 1, 1, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 0, 0, 1],
    [1, 0, 1, 1, 0, 0, 1, 1],
    [0, 1, 0, 1, 0, 1, 1, 0],
    [0, 0, 1, 0, 1, 0, 1, 1]
]
flat_input_bytes = [item for sublist in input_bytes for item in sublist]

byte_input = bytes(flat_input_bytes)
print("h-Hash", _h(byte_input))
binary_representation = ''.join(f'{byte:08b}' for byte in _h(byte_input))
print("lentgh", len(binary_representation))

print("Binary representation:", binary_representation)