# -*- coding: utf-8 -*-
"""G-Hash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOmLKCjTTQFcCQN0jVXk1MlPGiWqsPlu
"""

from hashlib import sha512

def _g(input_bytes):
    """
    G: B* -> B^32 * B^32
    """
    return sha512(input_bytes).digest()

input_bytes = [
    [1, 1, 1, 1, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 0, 0, 1],
    [1, 0, 1, 1, 0, 0, 1, 1],
    [0, 1, 0, 1, 0, 1, 1, 0],
    [0, 0, 1, 0, 1, 0, 1, 1]
]
flat_input_bytes = [item for sublist in input_bytes for item in sublist]

byte_input = bytes(flat_input_bytes)
print("g-Hash", _g(byte_input))
binary_representation = ''.join(f'{byte:08b}' for byte in _g(byte_input))

print("lentgh", len(binary_representation))

print("Binary representation:", binary_representation)
rho, sigma = binary_representation[:256], binary_representation[256:]
print("rho",rho)
print("sigma",sigma)

