# -*- coding: utf-8 -*-
"""G-Hash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOmLKCjTTQFcCQN0jVXk1MlPGiWqsPlu
"""

from hashlib import sha512

def _g(input_bytes):
    """
    G: B* -> B^32 * B^32
    """
    return sha512(input_bytes).digest()

input_bytes = b'+\x86\xbfd\xd3\xf4\x14y\x06\x9a\\Y\x0f_\xff4'



