# -*- coding: utf-8 -*-
"""G-Hash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOmLKCjTTQFcCQN0jVXk1MlPGiWqsPlu
"""

from hashlib import sha512

def _g(input_bytes):
    """
    G: B* -> B^32 * B^32
    """
    return sha512(input_bytes).digest()

input_bytes = b'+\x86\xbfd\xd3\xf4\x14y\x06\x9a\\Y\x0f_\xff4'
# print (_g(input_bytes))
# flat_input_bytes = [item for sublist in input_bytes for item in sublist]

# byte_input = bytes(flat_input_bytes)
# binary_representation = ''.join(f'{byte:08b}' for byte in _g(byte_input))

# rho, sigma = binary_representation[:256], binary_representation[256:]


